#! /bin/bash

set -x
#DEBHELPER#

function config_system_reboot() {
	if [ ! -f /etc/modules-load.d/cstat_percpu.conf ] ; then
		touch /etc/modules-load.d/cstat_percpu.conf
	fi

	if [ `grep -c "cgv2_stat_percpu" /etc/modules-load.d/cstat_percpu.conf` -eq '0' ]; then
		echo "cgv2_stat_percpu" > /etc/modules-load.d/cstat_percpu.conf
	fi
}

lsmod | grep "cgv2_stat_percpu"
if [ $? -ne 0 ] ; then
	echo "grep return a none-zero value, not find cgv2_stat_percpu"
else
	rmmod cgv2_stat_percpu.ko
	echo "grep return zero value, find cgv2_stat_percpu"
fi

config_system_reboot

modprobe cgv2_stat_percpu
exit 0
